name: migration_validation
version: "1.8.0"
config-version: 2
profile: migration_target
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]
models:
  migration_validation:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
